language: go

go:
  - "1.12"

os:
  - linux
  # This got a segfault on Travis but not on local Windows machine, 2019-10-06
  #- windows
  # Doesn't work, "An invalid error was not accepted by the caller: FormatUnavailable: NSGL: Failed to find a suitable pixel format"
  #- osx

services:
  - xvfb

install:
  - export GO111MODULE=on

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libasound2-dev
      - libgl1-mesa-dev
      - libalut-dev
      - libxcursor-dev
      - libxi-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxxf86vm-dev

script:
  - go test -v ./...
